"""add the col max_streak

Revision ID: 69e3b8f8055e
Revises: fd110737fa9b
Create Date: 2025-02-20 23:45:20.839873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e3b8f8055e'
down_revision = 'fd110737fa9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_read', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_streak', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_read', schema=None) as batch_op:
        batch_op.drop_column('max_streak')

    # ### end Alembic commands ###
