"""Adicionando valores padrão para UTM

Revision ID: 8b34851acc4a
Revises: 
Create Date: 2025-02-16 21:23:59.132103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b34851acc4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_read', schema=None) as batch_op:
        batch_op.alter_column('utm_source',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('utm_medium',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('utm_campaign',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('utm_channel',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_read', schema=None) as batch_op:
        batch_op.alter_column('utm_channel',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('utm_campaign',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('utm_medium',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('utm_source',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
