"""Adicionar coluna max_streak

Revision ID: ea83831bf14a
Revises: 8b34851acc4a
Create Date: 2025-02-18 19:42:19.779216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea83831bf14a'
down_revision = '8b34851acc4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_read', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_streak', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_read', schema=None) as batch_op:
        batch_op.drop_column('max_streak')

    # ### end Alembic commands ###