"""add the new column current_streak

Revision ID: fa3eac5d8d66
Revises: 69e3b8f8055e
Create Date: 2025-02-22 17:15:45.773257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa3eac5d8d66'
down_revision = '69e3b8f8055e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_read', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_streak', sa.Integer(), nullable=True))
        batch_op.create_index('ix_newsletter_read_email_timestamp', ['email', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_newsletter_read_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_read', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newsletter_read_timestamp'))
        batch_op.drop_index('ix_newsletter_read_email_timestamp')
        batch_op.drop_column('current_streak')

    # ### end Alembic commands ###
