"""create a table  newsletter_read

Revision ID: fd110737fa9b
Revises: 
Create Date: 2025-02-20 00:42:25.537574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd110737fa9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter_read',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('post_id', sa.String(length=255), nullable=False),
    sa.Column('utm_source', sa.String(length=50), nullable=False),
    sa.Column('utm_medium', sa.String(length=50), nullable=False),
    sa.Column('utm_campaign', sa.String(length=50), nullable=False),
    sa.Column('utm_channel', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('streak', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('newsletter_read', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_newsletter_read_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_newsletter_read_post_id'), ['post_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_read', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newsletter_read_post_id'))
        batch_op.drop_index(batch_op.f('ix_newsletter_read_email'))

    op.drop_table('newsletter_read')
    # ### end Alembic commands ###
